name: MMLuck
version: ${project.version}
main: com.github.mori01231.mmluck.MMLuck
api-version: 1.15

commands:
  mythicluckgive:
    description: MythicLuckの基本コマンド。
    aliases: [mlg, mythiclg, mythicluckg, mlgive]
    permission: MMLuck.mlg
    usage: エラー。/mlg プレイヤー名 アイテム名 確率 個数 で使用できます。
  mythicluckgiveoverflow:
    description: MythicLuckの基本コマンド。
    aliases: [mlgo, mythiclgo, mythicluckgo, mlgiveo,mlgoverflow]
    permission: MMLuck.mlgo
    usage: エラー。/mlgo プレイヤー名 アイテム名 確率 個数 で使用できます。

permissions:
  MMLuck.*:
    description: MythicLuckの全コマンドへのアクセスを可能にする。
    default: true
    children:
      MMLuck.mlg: true
      MMLuck.mlgo: true
  MMLuck.mlg:
    description: Allows you to use /mlg command.
    default: false
  MMLuck.mlgo:
    description: Allows you to use /mlg command.
    default: false