name: MMLuck
version: ${project.version}
main: com.github.mori01231.mmluck.MMLuck
api-version: 1.15
depend:
  - LifeCore
  - MythicMobs
  - Rarity

commands:
  mythicluckgive:
    description: MythicLuckの基本コマンド。
    aliases: [mlg, mythiclg, mythicluckg, mlgive]
    permission: MMLuck.mlg
    usage: エラー。/mlg プレイヤー名 アイテム名 確率 個数 で使用できます。
  mythicluckgiveoverflow:
    description: MythicLuckの基本コマンド。
    aliases: [mlgo, mythiclgo, mythicluckgo, mlgiveo,mlgoverflow]
    permission: MMLuck.mlgo
    usage: エラー。/mlgo プレイヤー名 アイテム名 確率 個数 で使用できます。
  addboosttime:
    description: ドロップ率ブーストを追加。
    aliases: [abt]
    permission: MMLuck.abt
    usage: エラー。/abt 効果時間(秒) 効果レベル（%）で使用できます。
  broadcastboost:
    description: ドロップ率ブーストを鯖内にアナウンス。
    permission: MMLuck.broadcastboost
    usage: エラー。/broadcastboost で使用できます。
  checkboost:
    description: ドロップ率ブーストを確認。
    aliases: [cb]
    permission: MMLuck.checkboost
    usage: エラー。/checkboost で使用できます。
  mythiclucksilent:
    aliases: [mls, mythicls, mythiclucks, mmlucksilent]
    permission: MMLuck.mls
  giveboostitem:
    permission: mmluck.giveboostitem

permissions:
  MMLuck.*:
    description: MythicLuckの全コマンドへのアクセスを可能にする。
    default: true
    children:
      MMLuck.mlg: true
      MMLuck.mlgo: true
      MMLuck.abt: true
      MMLuck.broadcastboost: true
      MMLuck.checkboost: true
      mmluck.giveboostitem: true
  MMLuck.mlg:
    description: Allows you to use /mlg command.
    default: false
  MMLuck.mlgo:
    description: Allows you to use /mlgo command.
    default: false
  MMLuck.abt:
    description: Allows you to use /abt command.
    default: false
  MMLuck.broadcastboost:
    description: Allows you to use /broadcastboost command.
    default: false
  MMLuck.checkboost:
    description: Allows you to use /checkboost command.
    default: false
  MMLuck.mls:
    description: "Allows you to use /mls command."
    default: true
  mmluck.giveboostitem:
    description: "Allows you to use /giveboostitem command."
    default: false
